### ISSUE TITLE
Expose ports that composed services were started on

### ISSUE THREAD

**Issue by checketts** [dkanejs/docker-compose-maven-plugin#26]
I need a way to detect what port was used for the started containers. This is needed when the port is left off the compose file to allow it to be dynamic (and avoid collisions on the build server)

Example `docker-compose.yml`:
```
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: example
```

The [gradle equivalent](https://github.com/avast/gradle-docker-compose-plugin#quick-start) exposes the port as an environment variable. So with the MySQL example above, it would be exposed at `DB_TCP_3306`.
